### ISSUE TITLE
The website of dataset is down?

### ISSUE THREAD

**Issue by guohengkai** [cvlab-epfl/disk#10]
Hi,

I'm trying to download the MegaDepth training dataset using your script. But I found that the website is down. Do you have any idea about it?

Thank you very much.

**Comment by guohengkai** [comment]
It is recovered now.

**Comment by kourner** [comment]
hi @guohengkai, https://datasets.epfl.ch/disk-data/index.html is down, can you share the dataset to me? thank you very much!
