### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by Lucifer1002** [cvlab-epfl/disk#15]
Hello, what is the specific version number of each library in requirements.txt

**Comment by jatentaki** [comment]
Honest answer: I don't remember. Are you facing any issues with running the code? If so, I'd try versions from ~2 years ago (for example PyTorch 1.7.1).

**Comment by Lucifer1002** [comment]
When I run the detect.py and view.py files, it only shows 0it [00:00, ?it/s] without any result output, what is the possible reason? Thanks for your answer.

**Comment by jatentaki** [comment]
What are the file names? The default for "--image extension" is "jpg", perhaps your images are called differently (jpeg, JPG, png)? That, alongside with potentially pointing the script to the wrong directory are the main suspects, library version mismatch is rather unlikely as the reason.

**Comment by Lucifer1002** [comment]
Thank you for your patience, I have found the problem
