### ISSUE TITLE
How to get matched keypoints

### ISSUE THREAD

**Issue by Draconda** [cvlab-epfl/disk#16]
Hi, thank you for opensourcing such a great model,

I'm now trying to run keypoint matching between two images ("image_0.png", "image_1.png"), and set those images into the directory ./pairs
, & created outputs directory of h5 files ./output
, & set contents of this repo codes ./ too,
I ran 

python detect.py output ./pairs
python match.py output

and seems it worked & created

`ls output`

  descriptors.h5	keypoints.h5  matches.h5
  
, but when I checked with 

`keypoint_f = h5py.File('output/keypoints.h5', 'r')`
, it doesn't contain any keys,
is it working fine?

thanks a lot,

**Comment by jatentaki** [comment]
Hey, by default `detect.py` handles files ending in `jpg`. You can run the script with `--image-extension png` and it should detect all images of interest :) (note this is case-sensitive)

**Comment by Draconda** [comment]
Thank you for your reply,
Okay, I'll try with it,
thanks again!! ;)
