### ISSUE TITLE
descriptor

### ISSUE THREAD

**Issue by Lucifer1002** [cvlab-epfl/disk#17]
Hello, regarding the descriptor of DISK, do you have a 256-dimensional preprocessing model?

**Comment by jatentaki** [comment]
Hey, sorry for the wait. The answer is no, we don't. We ran experiments with 128, 64, 32 and 16 dimensions and found that the performance drop with 64 (and even 32) is very small, it was only 16-dim descriptor that performed significantly worse. For this reason we did not try scaling up the descriptors, as it seemed to have little value. You're obviously free to do that though! Please be aware you may want to adjust the [unet settings](https://github.com/cvlab-epfl/disk/blob/master/disk/model/disk.py#L23) to make the architecture fatter overall. 

PS I should be able to find the lower-dimensional models if you're interested.
