### ISSUE TITLE
question about the training result

### ISSUE THREAD

**Issue by KN-Zhang** [cvlab-epfl/disk#18]
Hello~ I wonder the performance of the final models would be similar or different  when I train the network from scratch each time.  Have you ever evaluated this issue?
Thanks.

**Comment by jatentaki** [comment]
Hello, what exactly do you mean by "each time"? On a different dataset? Or are you just asking about reproducibility on the dataset we trained with?

**Comment by KN-Zhang** [comment]
> Hello, what exactly do you mean by "each time"? On a different dataset? Or are you just asking about reproducibility on the dataset we trained with?

I mean the reproducibility with the same dataset.

**Comment by jatentaki** [comment]
Ok, is your question not covered by the relevant section of [readme](https://github.com/cvlab-epfl/disk#reproducing-our-results)? In short, yes, it should be easily reproducible up to 0.50432 stereo AUC and 0.72624 multiview AUC on IMW2020 test set and up to the paper results with the slightly more involved schedule explained in that paragraph. Are you seeing different results on your end?

**Comment by KN-Zhang** [comment]
> Ok, is your question not covered by the relevant section of [readme](https://github.com/cvlab-epfl/disk#reproducing-our-results)? In short, yes, it should be easily reproducible up to 0.50432 stereo AUC and 0.72624 multiview AUC on IMW2020 test set and up to the paper results with the slightly more involved schedule explained in that paragraph. Are you seeing different results on your end?

In fact I just began to train the model and haven't performed evaluation. Due to the nature of sampling, the variances of all metrics (for example ”n_keypoints“, "n_pairs" during the training stage) are very large. So I am curious whether the performance among each trained model would vary. 

Thanks for your response! I would track this issue if different results were saw on my end.

**Comment by jatentaki** [comment]
Yes, the variance of the training metrics is very large indeed, but we found the validation numbers (averaged across the entire set) to be quite reliable. Please reopen if you find any major discrepancies :)
