### ISSUE TITLE
Using mp.Pool can cause the training process to get stuck.

### ISSUE THREAD

**Issue by Martin0Li** [cvlab-epfl/disk#22]
Currently using DummyPool as a replacement, and no better solution has been found yet.

**Comment by jatentaki** [comment]
Hi, the implementation is indeed incorrect in terms of how python `multiprocessing` should be used but it never caused any issues on my hardware. I pushed a fix to the `pool-issues` branch of repository. Please see if that resolves the issue for you and if so, I will merge it to master.

**Comment by Martin0Li** [comment]
It works.

**Comment by jatentaki** [comment]
Thanks, now it's on master :)
