### ISSUE TITLE
Missing data request

### ISSUE THREAD

**Issue by 1chimaruGin** [cvlab-epfl/disk#26]
Thank you for amazing work! 

During dataset download some of the scenes seem to be corrupted. I tried to download Megadepth DISK dataset from website and it is down. 😢 

Could you please provide these scenes? The missing files are `["0411", "0472", "0476", "0478", '0482']`

**Comment by jatentaki** [comment]
Hi, the dataset should be back up. Can you confirm?

**Comment by 1chimaruGin** [comment]
Yes, the dataset website is back online. 💯
