### ISSUE TITLE
dataset request

### ISSUE THREAD

**Issue by kourner** [cvlab-epfl/disk#27]
Excellent work, I would like to conduct further research based on this work. However, the official website for the megadepth disk dataset has been shut down, making it impossible to download. Could anyone share the megadepth disk dataset? I am willing to pay for it.

**Comment by jatentaki** [comment]
Hello Kourner, the dataset should be back up. Please let me know if you can access it.

**Comment by kourner** [comment]
> Hello Kourner, the dataset should be back up. Please let me know if you can access it.

Thanks a million, i can get it now!

**Comment by ruanyan0916** [comment]
> 干得好！我想基于这项工作进行进一步的研究。但是，超深度磁盘数据集的官方网站已经关闭，无法下载。有人可以分享超深度磁盘数据集吗？我愿意付费购买。
  I would like to conduct further research based on this work. However, the official website for the megadepth disk dataset has been shut down, making it impossible to download. Could you share the disk dataset?
