### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by ducha-aiki** [cvlab-epfl/disk#3]

**Comment by ConvMech** [comment]
wish it's mit

**Comment by jatentaki** [comment]
I have just uploaded a LICENSE.txt file. Per EPFL guidelines, we release this under the GPL v3 license and are open to licensing it on different terms on a case-by-case basis (in particular for commercial use).

**Comment by ducha-aiki** [comment]
Thank you!

P.S. Btw, GPL v3 does not prohibit commercial usage, unless one wants to release the modified version under other license :)
