### ISSUE TITLE
AttributeError: 'JpegImageFile' object has no attribute 'getexif'

### ISSUE THREAD

**Issue by tudipffmgt** [cvlab-epfl/disk#8]
Hi and thanks for your work!
I ran your pipeline **Exporting to COLMAP**
When I used the script h5_to_db.py I ran into the following issue:

> Traceback (most recent call last):
>   File "colmap/h5_to_db.py", line 145, in <module>
>     fname_to_id = add_keypoints(db, args.h5_path, args.image_path)
>   File "colmap/h5_to_db.py", line 72, in add_keypoints
>     camera_id = create_camera(db, path)
>   File "colmap/h5_to_db.py", line 40, in create_camera
>     focal = get_focal(image_path)
>   File "colmap/h5_to_db.py", line 12, in get_focal
>     exif = image.getexif()
> AttributeError: 'JpegImageFile' object has no attribute 'getexif'

So I changed line 12 to `exif = image._getexif()` (added an underscore) and the pipeline worked. Maybe it is helpful for others.

**Comment by jatentaki** [comment]
Great, thanks :) I think this is related to the version of h5py.
